// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/audaudio_github_io_version.spec.ts.

/** The version of the `audaudio.github.io` package. */
export const audaudioGithubIoVersion = '0.4.0';
